# Kickstart container config file - see https://nfra.infracamp.org
# Run kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"

# Add List of packages to install (apt-get install) as Array or ~ for none
packages: ~

# Create a config file from a template using the environment variables
config_file:
    template: "config.php.dist"
    target: "config.php"

command:
  build:
    - "composer update"
  init:
  test:
    - "ptest"
  run:


